### ISSUE TITLE
Need to Import Nessus Scans

### ISSUE THREAD

**Issue by theshades** [ShadeySecurity/pyAssetInventory#3]
Need to import Nessus Scan results and make it useful. As part of this, need to add a software column in the database or a separate datbase with ip and software.

**Comment by theshades** [comment]
Looks like we need to simply inject an module for https://pypi.python.org/pypi/python-libnessus/1.0.0.3

**Comment by wasupmang** [comment]
ah yup looks easy I'll test it out today!

**Comment by theshades** [comment]
Be sure you read https://github.com/ShadeySecurity/AssetInventory/blob/master/models/db.py#L145 and below to understand the new database structures. I would also recommend you look at the importintodb() function in the default controller! Let me know if any questions or concerns man!

**Comment by theshades** [comment]
Hold up one more time... need to split the databases out one more time.

**Comment by theshades** [comment]
#6  is blocking.

**Comment by theshades** [comment]
@wasupmang  you are now unblocked :) All I need from you is either A) a nested dictionary or B) an object (with some docs on how to access it's data). I prefer dictionaries as if you dont know how to access it... you just print it out :D

**Comment by theshades** [comment]
Started on your file for you, you can the xml specification here:
https://static.tenable.com/documentation/nessus_v2_file_format.pdf
The file I already worked on is pynessusasset.py.
I'll leave the rest for you if you are able, if not I can finish it off fairly well... I just dont have a nessus xml file to work against.
Look at pynmap.py if you need ideas on what I am looking for... close as you can resemble the output to that of pynmap.py... the less work I have to do on the front end... which is good idea it is already a good amount of work there.

**Comment by wasupmang** [comment]
Yup I'll take a look at it! I left my stuff at work and I don't work
Fridays!

**Comment by theshades** [comment]
@wasupmang no worries man :) Just keeping you in the loop as I had to do some of the work there in order to start working on my front-end work, and to make sure you knew what I was looking for. :)

**Comment by theshades** [comment]
I've bumped the due date for this as far as I can.
