### ISSUE TITLE
Automagic Network Map

### ISSUE THREAD

**Issue by theshades** [ShadeySecurity/pyAssetInventory#5]
It would be handy to create a simple network map of hosts and what ports open they have.

**Comment by tom234679** [comment]
I would be game to help with this one. I actually had an elaborate plan for doing this already. I'll rework and develop to fit the project

**Comment by theshades** [comment]
@ITredneck I'll give you a shot man! Good luck! :) Talking about learning by fire... this will probably be the hardest part.
